services:
  app:
    build: .
    container_name: banister_app
    restart: always
    env_file:
      - .env
    volumes:
      - banister_data:/app/data
    ports:
      - "127.0.0.1:8000:8000"

volumes:
  banister_data:
