"""wellness and sync state

Revision ID: 0d2cb3557233
Revises: ecd6f700779f
Create Date: 2026-08-27 16:41:02.477069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '0d2cb3557233'
down_revision: Union[str, Sequence[str], None] = 'ecd6f700779f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reported_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_activity_id', sa.String(length=64), nullable=False),
    sa.Column('reported_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_activity_id', name='uq_reported_activity_user_source_id')
    )
    op.create_index(op.f('ix_reported_activities_user_id'), 'reported_activities', ['user_id'], unique=False)
    op.create_table('sync_state',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_successful_refresh_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('history_import_cursor_date', sa.Date(), nullable=True),
    sa.Column('history_import_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_state_user_id'), 'sync_state', ['user_id'], unique=True)
    op.create_table('wellness',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hrv', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.SmallInteger(), nullable=True),
    sa.Column('sleep_seconds', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('ctl', sa.Float(), nullable=True),
    sa.Column('atl', sa.Float(), nullable=True),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_wellness_user_date')
    )
    op.create_index(op.f('ix_wellness_user_id'), 'wellness', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wellness_user_id'), table_name='wellness')
    op.drop_table('wellness')
    op.drop_index(op.f('ix_sync_state_user_id'), table_name='sync_state')
    op.drop_table('sync_state')
    op.drop_index(op.f('ix_reported_activities_user_id'), table_name='reported_activities')
    op.drop_table('reported_activities')
    # ### end Alembic commands ###
