"""session_log efficiency_factor and hrr

Revision ID: 3554291e7637
Revises: 40fc251ea272
Create Date: 2026-09-21 02:13:48.659323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '3554291e7637'
down_revision: Union[str, Sequence[str], None] = '40fc251ea272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_logs', sa.Column('efficiency_factor', sa.Float(), nullable=True))
    op.add_column('session_logs', sa.Column('hrr', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_logs', 'hrr')
    op.drop_column('session_logs', 'efficiency_factor')
    # ### end Alembic commands ###
