"""coach_journal_entries

Revision ID: 40fc251ea272
Revises: b7cb3fb04f0c
Create Date: 2026-09-20 16:19:58.428231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '40fc251ea272'
down_revision: Union[str, Sequence[str], None] = 'b7cb3fb04f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_journal_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('occurred_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coach_journal_user_date', 'coach_journal_entries', ['user_id', 'entry_date'], unique=False)
    op.create_index(op.f('ix_coach_journal_entries_user_id'), 'coach_journal_entries', ['user_id'], unique=False)
    op.create_index('uq_coach_journal_dedup', 'coach_journal_entries', ['user_id', 'entry_date', 'category', 'dedup_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_coach_journal_dedup', table_name='coach_journal_entries')
    op.drop_index(op.f('ix_coach_journal_entries_user_id'), table_name='coach_journal_entries')
    op.drop_index('idx_coach_journal_user_date', table_name='coach_journal_entries')
    op.drop_table('coach_journal_entries')
    # ### end Alembic commands ###
