"""add token usage columns to chat_messages

Revision ID: 5bb13e8b1b93
Revises: ec93c120b7ab
Create Date: 2026-09-18 02:20:37.167788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '5bb13e8b1b93'
down_revision: Union[str, Sequence[str], None] = 'ec93c120b7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('tokens_input', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('tokens_output', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'tokens_output')
    op.drop_column('chat_messages', 'tokens_input')
    # ### end Alembic commands ###
