"""spec_008_meal_entries

Revision ID: 5f944592c853
Revises: a8a7d1b9fb05
Create Date: 2026-09-15 23:49:02.578914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '5f944592c853'
down_revision: Union[str, Sequence[str], None] = 'a8a7d1b9fb05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.String(length=16), nullable=False),
    sa.Column('meal_slot', sa.String(length=16), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('estimated_calories', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meal_entries_user_date', 'meal_entries', ['user_id', 'entry_date'], unique=False)
    op.create_index(op.f('ix_meal_entries_user_id'), 'meal_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_entries_user_id'), table_name='meal_entries')
    op.drop_index('idx_meal_entries_user_date', table_name='meal_entries')
    op.drop_table('meal_entries')
    # ### end Alembic commands ###
