"""spec 005 publication tables

Revision ID: 81cf8110ef26
Revises: c14c84776008
Create Date: 2026-08-28 21:18:52.842107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '81cf8110ef26'
down_revision: Union[str, Sequence[str], None] = 'c14c84776008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('horizon_start', sa.Date(), nullable=False),
    sa.Column('horizon_end', sa.Date(), nullable=False),
    sa.Column('session_count', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('decided_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_publication_approvals_user_status', 'publication_approvals', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_publication_approvals_plan_id'), 'publication_approvals', ['plan_id'], unique=False)
    op.create_index(op.f('ix_publication_approvals_user_id'), 'publication_approvals', ['user_id'], unique=False)
    op.create_table('published_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('approval_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('intervals_event_id', sa.String(length=32), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('week_number', sa.SmallInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['publication_approvals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'external_id', name='uq_published_entries_user_external_id')
    )
    op.create_index('idx_published_entries_plan', 'published_entries', ['plan_id'], unique=False)
    op.create_index(op.f('ix_published_entries_user_id'), 'published_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_published_entries_user_id'), table_name='published_entries')
    op.drop_index('idx_published_entries_plan', table_name='published_entries')
    op.drop_table('published_entries')
    op.drop_index(op.f('ix_publication_approvals_user_id'), table_name='publication_approvals')
    op.drop_index(op.f('ix_publication_approvals_plan_id'), table_name='publication_approvals')
    op.drop_index('idx_publication_approvals_user_status', table_name='publication_approvals')
    op.drop_table('publication_approvals')
    # ### end Alembic commands ###
