"""session_log rpe numeric scale replaces rpe_emoji

Revision ID: 9055a9201366
Revises: aaa58b43f734
Create Date: 2026-09-21 14:01:19.302020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '9055a9201366'
down_revision: Union[str, Sequence[str], None] = 'aaa58b43f734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_logs', sa.Column('rpe', sa.Float(), nullable=True))
    # Backfill depuis l'ancien catégoriel avant de le perdre — valeurs représentatives
    # de app/engine/rpe.py (RPE_EASY_VALUE/RPE_NORMAL_VALUE/RPE_HARD_VALUE), pas une
    # commande auto-générée : les données existantes ne doivent pas silencieusement
    # devenir NULL.
    op.execute(
        "UPDATE session_logs SET rpe = CASE rpe_emoji "
        "WHEN 'hard' THEN 8 WHEN 'normal' THEN 5 WHEN 'easy' THEN 2 ELSE NULL END "
        "WHERE rpe_emoji IS NOT NULL"
    )
    op.drop_column('session_logs', 'rpe_emoji')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_logs', sa.Column('rpe_emoji', sa.VARCHAR(length=8), nullable=True))
    # Reconversion approximative — mêmes bandes que app/engine/rpe.py
    # (RPE_HARD_MIN=7.0 / RPE_EASY_MAX=3.0). Non bijective avec l'upgrade (un rpe=6
    # devient 'normal' puis remonterait à 5, pas 6) — un downgrade n'est déjà pas conçu
    # pour restaurer le chiffre exact source, seulement la bande.
    op.execute(
        "UPDATE session_logs SET rpe_emoji = CASE "
        "WHEN rpe >= 7.0 THEN 'hard' WHEN rpe <= 3.0 THEN 'easy' "
        "WHEN rpe IS NOT NULL THEN 'normal' ELSE NULL END"
    )
    op.drop_column('session_logs', 'rpe')
    # ### end Alembic commands ###
