"""spec 007 users coach_voice and disclaimer_acknowledged_at

Revision ID: a8a7d1b9fb05
Revises: ebfb7e00afa1
Create Date: 2026-09-01 22:50:56.197380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'a8a7d1b9fb05'
down_revision: Union[str, Sequence[str], None] = 'ebfb7e00afa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coach_voice', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('disclaimer_acknowledged_at', app.db.types.UtcDateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disclaimer_acknowledged_at')
    op.drop_column('users', 'coach_voice')
    # ### end Alembic commands ###
