"""wellness raw fields from intervals.icu

Revision ID: aaa58b43f734
Revises: 3554291e7637
Create Date: 2026-09-21 02:15:06.401022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'aaa58b43f734'
down_revision: Union[str, Sequence[str], None] = '3554291e7637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellness', sa.Column('hrv_sdnn', sa.Float(), nullable=True))
    op.add_column('wellness', sa.Column('sleep_quality', sa.SmallInteger(), nullable=True))
    op.add_column('wellness', sa.Column('sleep_score', sa.SmallInteger(), nullable=True))
    op.add_column('wellness', sa.Column('mental_energy', sa.SmallInteger(), nullable=True))
    op.add_column('wellness', sa.Column('avg_sleeping_hr', sa.SmallInteger(), nullable=True))
    op.add_column('wellness', sa.Column('vo2max', sa.Float(), nullable=True))
    op.add_column('wellness', sa.Column('fatigue', sa.SmallInteger(), nullable=True))
    op.add_column('wellness', sa.Column('soreness', sa.SmallInteger(), nullable=True))
    op.add_column('wellness', sa.Column('stress', sa.SmallInteger(), nullable=True))
    op.add_column('wellness', sa.Column('mood', sa.SmallInteger(), nullable=True))
    op.add_column('wellness', sa.Column('motivation', sa.SmallInteger(), nullable=True))
    op.add_column('wellness', sa.Column('injury', sa.SmallInteger(), nullable=True))
    op.add_column('wellness', sa.Column('hydration', sa.SmallInteger(), nullable=True))
    op.add_column('wellness', sa.Column('spo2', sa.Float(), nullable=True))
    op.add_column('wellness', sa.Column('blood_glucose', sa.Float(), nullable=True))
    op.add_column('wellness', sa.Column('systolic', sa.SmallInteger(), nullable=True))
    op.add_column('wellness', sa.Column('diastolic', sa.SmallInteger(), nullable=True))
    op.add_column('wellness', sa.Column('baevsky_si', sa.Float(), nullable=True))
    op.add_column('wellness', sa.Column('lactate', sa.Float(), nullable=True))
    op.add_column('wellness', sa.Column('respiration', sa.Float(), nullable=True))
    op.add_column('wellness', sa.Column('body_fat_pct', sa.Float(), nullable=True))
    op.add_column('wellness', sa.Column('abdomen_cm', sa.Float(), nullable=True))
    op.add_column('wellness', sa.Column('steps', sa.Integer(), nullable=True))
    op.add_column('wellness', sa.Column('hydration_volume_l', sa.Float(), nullable=True))
    op.add_column('wellness', sa.Column('kcal_consumed', sa.Integer(), nullable=True))
    op.add_column('wellness', sa.Column('carbohydrates_g', sa.Float(), nullable=True))
    op.add_column('wellness', sa.Column('protein_g', sa.Float(), nullable=True))
    op.add_column('wellness', sa.Column('fat_g', sa.Float(), nullable=True))
    op.add_column('wellness', sa.Column('menstrual_phase', sa.String(length=16), nullable=True))
    op.add_column('wellness', sa.Column('menstrual_phase_predicted', sa.String(length=16), nullable=True))
    op.add_column('wellness', sa.Column('readiness', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wellness', 'readiness')
    op.drop_column('wellness', 'menstrual_phase_predicted')
    op.drop_column('wellness', 'menstrual_phase')
    op.drop_column('wellness', 'fat_g')
    op.drop_column('wellness', 'protein_g')
    op.drop_column('wellness', 'carbohydrates_g')
    op.drop_column('wellness', 'kcal_consumed')
    op.drop_column('wellness', 'hydration_volume_l')
    op.drop_column('wellness', 'steps')
    op.drop_column('wellness', 'abdomen_cm')
    op.drop_column('wellness', 'body_fat_pct')
    op.drop_column('wellness', 'respiration')
    op.drop_column('wellness', 'lactate')
    op.drop_column('wellness', 'baevsky_si')
    op.drop_column('wellness', 'diastolic')
    op.drop_column('wellness', 'systolic')
    op.drop_column('wellness', 'blood_glucose')
    op.drop_column('wellness', 'spo2')
    op.drop_column('wellness', 'hydration')
    op.drop_column('wellness', 'injury')
    op.drop_column('wellness', 'motivation')
    op.drop_column('wellness', 'mood')
    op.drop_column('wellness', 'stress')
    op.drop_column('wellness', 'soreness')
    op.drop_column('wellness', 'fatigue')
    op.drop_column('wellness', 'vo2max')
    op.drop_column('wellness', 'avg_sleeping_hr')
    op.drop_column('wellness', 'mental_energy')
    op.drop_column('wellness', 'sleep_score')
    op.drop_column('wellness', 'sleep_quality')
    op.drop_column('wellness', 'hrv_sdnn')
    # ### end Alembic commands ###
