"""add users.onboarding_completed_at

Revision ID: b04fa2551cf0
Revises: 36146a67fa90
Create Date: 2026-08-27 21:38:33.884441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'b04fa2551cf0'
down_revision: Union[str, Sequence[str], None] = '36146a67fa90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_completed_at', app.db.types.UtcDateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed_at')
    # ### end Alembic commands ###
