"""widen activity source_activity_id to string

Revision ID: b24778c0a229
Revises: 0d2cb3557233
Create Date: 2026-08-27 17:08:38.147329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'b24778c0a229'
down_revision: Union[str, Sequence[str], None] = '0d2cb3557233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-edited from the autogenerated form: plain op.alter_column() emits
    `ALTER TABLE ... ALTER COLUMN ... TYPE ...`, which SQLite's grammar does not have
    (confirmed directly: `OperationalError: near "ALTER": syntax error` running the
    autogenerated version against a scratch db). SQLite only supports column-type
    changes via batch mode (recreate-and-copy), which op.batch_alter_table drives.
    """
    with op.batch_alter_table('activities') as batch_op:
        batch_op.alter_column(
            'source_activity_id',
            existing_type=sa.BIGINT(),
            type_=sa.String(length=64),
            existing_nullable=True,
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('activities') as batch_op:
        batch_op.alter_column(
            'source_activity_id',
            existing_type=sa.String(length=64),
            type_=sa.BIGINT(),
            existing_nullable=True,
        )
