"""spec 010 freestyle published entries table

Revision ID: b7cb3fb04f0c
Revises: 5bb13e8b1b93
Create Date: 2026-09-18 10:36:52.096064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'b7cb3fb04f0c'
down_revision: Union[str, Sequence[str], None] = '5bb13e8b1b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freestyle_published_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('intervals_event_id', sa.String(length=32), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('workout_type', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'external_id', name='uq_freestyle_published_entries_user_external_id')
    )
    op.create_index(op.f('ix_freestyle_published_entries_user_id'), 'freestyle_published_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_freestyle_published_entries_user_id'), table_name='freestyle_published_entries')
    op.drop_table('freestyle_published_entries')
    # ### end Alembic commands ###
