"""widen session_log strava_activity_id to string

Revision ID: bdd28a28bbdb
Revises: b24778c0a229
Create Date: 2026-08-27 18:48:55.827102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'bdd28a28bbdb'
down_revision: Union[str, Sequence[str], None] = 'b24778c0a229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-edited from the autogenerated form, same reason as b24778c0a229: SQLite has no
    ALTER COLUMN TYPE, only batch mode (recreate-and-copy).
    """
    with op.batch_alter_table('session_logs') as batch_op:
        batch_op.alter_column(
            'strava_activity_id',
            existing_type=sa.BIGINT(),
            type_=sa.String(length=64),
            existing_nullable=True,
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('session_logs') as batch_op:
        batch_op.alter_column(
            'strava_activity_id',
            existing_type=sa.String(length=64),
            type_=sa.BIGINT(),
            existing_nullable=True,
        )
