"""rename session_log strava_activity_id to source_activity_id

Revision ID: c14c84776008
Revises: b04fa2551cf0
Create Date: 2026-08-27 22:00:44.223398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'c14c84776008'
down_revision: Union[str, Sequence[str], None] = 'b04fa2551cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-edited from the autogenerated form: Alembic can't detect a rename on its own
    and emitted add_column + drop_column, which would have silently discarded every
    existing value in this column (found live — this migration was missed originally,
    and the real fix is a true RENAME COLUMN, not add-then-drop).

    No batch mode needed: unlike a type change, both a bare column rename and an
    index drop/create are supported natively by SQLite — batch mode's table-recreation
    machinery only gets in the way here (tried first, and it does: batch mode tries to
    auto-migrate every index on the table using column names from *before* the rename
    takes effect, which raises `KeyError` on the new name).
    """
    op.execute("ALTER TABLE session_logs RENAME COLUMN strava_activity_id TO source_activity_id")
    op.drop_index(
        'idx_session_logs_strava_activity',
        table_name='session_logs',
        sqlite_where=sa.text('source_activity_id IS NOT NULL'),
    )
    op.create_index(
        'idx_session_logs_source_activity',
        'session_logs',
        ['source_activity_id'],
        sqlite_where=sa.text('source_activity_id IS NOT NULL'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        'idx_session_logs_source_activity',
        table_name='session_logs',
        sqlite_where=sa.text('source_activity_id IS NOT NULL'),
    )
    op.execute("ALTER TABLE session_logs RENAME COLUMN source_activity_id TO strava_activity_id")
    op.create_index(
        'idx_session_logs_strava_activity',
        'session_logs',
        ['strava_activity_id'],
        sqlite_where=sa.text('strava_activity_id IS NOT NULL'),
    )
