"""spec 006 guardrail tables and wellness ramp_rate

Revision ID: ebfb7e00afa1
Revises: 81cf8110ef26
Create Date: 2026-08-28 22:53:52.642126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'ebfb7e00afa1'
down_revision: Union[str, Sequence[str], None] = '81cf8110ef26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardrail_acknowledgements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('finding_kind', sa.String(length=32), nullable=False),
    sa.Column('occurrence_key', sa.String(length=128), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decided_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_guardrail_ack_user_occurrence', 'guardrail_acknowledgements', ['user_id', 'occurrence_key'], unique=False)
    op.create_index(op.f('ix_guardrail_acknowledgements_user_id'), 'guardrail_acknowledgements', ['user_id'], unique=False)
    op.create_table('response_check_failures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('failure_kind', sa.String(length=32), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('stated_value', sa.String(length=64), nullable=False),
    sa.Column('expected_value', sa.String(length=64), nullable=True),
    sa.Column('response_excerpt', sa.Text(), nullable=False),
    sa.Column('occurred_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_response_check_failures_user_time', 'response_check_failures', ['user_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_response_check_failures_user_id'), 'response_check_failures', ['user_id'], unique=False)
    op.add_column('wellness', sa.Column('ramp_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wellness', 'ramp_rate')
    op.drop_index(op.f('ix_response_check_failures_user_id'), table_name='response_check_failures')
    op.drop_index('idx_response_check_failures_user_time', table_name='response_check_failures')
    op.drop_table('response_check_failures')
    op.drop_index(op.f('ix_guardrail_acknowledgements_user_id'), table_name='guardrail_acknowledgements')
    op.drop_index('idx_guardrail_ack_user_occurrence', table_name='guardrail_acknowledgements')
    op.drop_table('guardrail_acknowledgements')
    # ### end Alembic commands ###
