"""spec 009 freestyle mode nullable session_log plan columns

Revision ID: ec93c120b7ab
Revises: 5f944592c853
Create Date: 2026-09-18 01:41:18.236423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'ec93c120b7ab'
down_revision: Union[str, Sequence[str], None] = '5f944592c853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-edited from the autogenerated form: plain op.alter_column() emits
    `ALTER TABLE ... ALTER COLUMN ...`, which SQLite's grammar does not have (confirmed
    directly: `OperationalError: near "ALTER": syntax error` running the autogenerated
    version against a scratch db — same issue b24778c0a229 hit). SQLite only supports
    nullability changes via batch mode (recreate-and-copy), which op.batch_alter_table
    drives; all three columns share one batch since they're on the same table.
    """
    with op.batch_alter_table('session_logs') as batch_op:
        batch_op.alter_column('plan_id', existing_type=sa.CHAR(length=32), nullable=True)
        batch_op.alter_column('week_number', existing_type=sa.SMALLINT(), nullable=True)
        batch_op.alter_column('day_of_week', existing_type=sa.SMALLINT(), nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('session_logs') as batch_op:
        batch_op.alter_column('day_of_week', existing_type=sa.SMALLINT(), nullable=False)
        batch_op.alter_column('week_number', existing_type=sa.SMALLINT(), nullable=False)
        batch_op.alter_column('plan_id', existing_type=sa.CHAR(length=32), nullable=False)
