"""baseline schema

Revision ID: ecd6f700779f
Revises: 
Create Date: 2026-08-27 12:04:54.763339

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types used across this project's models. Autogenerate renders these by
# fully-qualified path (app.db.types.UtcDateTime(...)) but does not reliably emit the
# import that path needs — observed directly: a first-attempt baseline referenced
# app.db.types.UtcDateTime with no import of `app` at all, a NameError at migration run
# time rather than a lint nit. A plain `import app.db.types` (not `from ... import`) is
# what the dotted-path reference actually requires, and covers every future migration.
import app.db.types  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = 'ecd6f700779f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reminders_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('reminder_hour', sa.SmallInteger(), nullable=False),
    sa.Column('reminder_minute', sa.SmallInteger(), nullable=False),
    sa.Column('reminder_last_sent_at', sa.Date(), nullable=True),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_activity_id', sa.BigInteger(), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('sport_type', sa.String(length=32), nullable=True),
    sa.Column('environment', sa.String(length=16), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('elevation_gain_meters', sa.Float(), nullable=True),
    sa.Column('avg_watts', sa.Float(), nullable=True),
    sa.Column('normalized_watts', sa.Float(), nullable=True),
    sa.Column('device_watts', sa.Boolean(), nullable=True),
    sa.Column('avg_heartrate', sa.Float(), nullable=True),
    sa.Column('max_heartrate', sa.Float(), nullable=True),
    sa.Column('suffer_score', sa.SmallInteger(), nullable=True),
    sa.Column('kilojoules', sa.Float(), nullable=True),
    sa.Column('tss', sa.Float(), nullable=True),
    sa.Column('tss_method', sa.String(length=16), nullable=True),
    sa.Column('ftp_used', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activities_source_id', 'activities', ['user_id', 'source', 'source_activity_id'], unique=True, postgresql_where=sa.text('source_activity_id IS NOT NULL'), sqlite_where=sa.text('source_activity_id IS NOT NULL'))
    op.create_index('idx_activities_user_date', 'activities', ['user_id', 'activity_date'], unique=False)
    op.create_index(op.f('ix_activities_activity_date'), 'activities', ['activity_date'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.create_table('athlete_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('coach_memory', sa.JSON(), nullable=False),
    sa.Column('athlete_notes', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_profiles_user_id'), 'athlete_profiles', ['user_id'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('tool_used', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages_user_created', 'chat_messages', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('oauth_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('provider_user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_oauth_user_provider')
    )
    op.create_index(op.f('ix_oauth_connections_user_id'), 'oauth_connections', ['user_id'], unique=False)
    op.create_table('training_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('plan_technical', sa.JSON(), nullable=False),
    sa.Column('plan_narrative', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_user_id'), 'training_plans', ['user_id'], unique=False)
    op.create_table('session_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('week_number', sa.SmallInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('logged_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rpe_emoji', sa.String(length=8), nullable=True),
    sa.Column('duration_minutes_actual', sa.SmallInteger(), nullable=True),
    sa.Column('tss_actual', sa.Float(), nullable=True),
    sa.Column('strava_activity_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=True),
    sa.Column('avg_heart_rate', sa.SmallInteger(), nullable=True),
    sa.Column('avg_power', sa.SmallInteger(), nullable=True),
    sa.Column('normalized_power', sa.SmallInteger(), nullable=True),
    sa.Column('kilojoules', sa.Float(), nullable=True),
    sa.Column('time_in_zones_s', sa.JSON(), nullable=True),
    sa.Column('cardiac_drift_index', sa.Float(), nullable=True),
    sa.Column('intervals_consistency_index', sa.Float(), nullable=True),
    sa.Column('respect_zones_score', sa.Float(), nullable=True),
    sa.Column('session_type_real', sa.String(length=16), nullable=True),
    sa.Column('variability_index', sa.Float(), nullable=True),
    sa.Column('intensity_factor', sa.Float(), nullable=True),
    sa.Column('dominant_zone', sa.String(length=4), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('average_temp_c', sa.Float(), nullable=True),
    sa.Column('athlete_count', sa.SmallInteger(), nullable=True),
    sa.Column('ctl_at_session', sa.Float(), nullable=True),
    sa.Column('atl_at_session', sa.Float(), nullable=True),
    sa.Column('tsb_at_session', sa.Float(), nullable=True),
    sa.Column('kpi_contribution', sa.Float(), nullable=True),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_logs_strava_activity', 'session_logs', ['strava_activity_id'], unique=False, postgresql_where=sa.text('strava_activity_id IS NOT NULL'), sqlite_where=sa.text('strava_activity_id IS NOT NULL'))
    op.create_index('idx_session_logs_user_date', 'session_logs', ['user_id', 'logged_date'], unique=False)
    op.create_index(op.f('ix_session_logs_logged_date'), 'session_logs', ['logged_date'], unique=False)
    op.create_index(op.f('ix_session_logs_plan_id'), 'session_logs', ['plan_id'], unique=False)
    op.create_index(op.f('ix_session_logs_user_id'), 'session_logs', ['user_id'], unique=False)
    op.create_table('weekly_adherence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('week_number', sa.SmallInteger(), nullable=True),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('sessions_done', sa.SmallInteger(), nullable=False),
    sa.Column('sessions_planned', sa.SmallInteger(), nullable=True),
    sa.Column('compliance_pct', sa.Float(), nullable=True),
    sa.Column('tss_7d', sa.Float(), nullable=False),
    sa.Column('computed_at', app.db.types.UtcDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start_date', name='uq_weekly_adherence_user_week')
    )
    op.create_index('idx_weekly_adherence_user_date', 'weekly_adherence', ['user_id', 'week_start_date'], unique=False)
    op.create_index(op.f('ix_weekly_adherence_user_id'), 'weekly_adherence', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_adherence_user_id'), table_name='weekly_adherence')
    op.drop_index('idx_weekly_adherence_user_date', table_name='weekly_adherence')
    op.drop_table('weekly_adherence')
    op.drop_index(op.f('ix_session_logs_user_id'), table_name='session_logs')
    op.drop_index(op.f('ix_session_logs_plan_id'), table_name='session_logs')
    op.drop_index(op.f('ix_session_logs_logged_date'), table_name='session_logs')
    op.drop_index('idx_session_logs_user_date', table_name='session_logs')
    op.drop_index('idx_session_logs_strava_activity', table_name='session_logs', postgresql_where=sa.text('strava_activity_id IS NOT NULL'), sqlite_where=sa.text('strava_activity_id IS NOT NULL'))
    op.drop_table('session_logs')
    op.drop_index(op.f('ix_training_plans_user_id'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_oauth_connections_user_id'), table_name='oauth_connections')
    op.drop_table('oauth_connections')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index('idx_chat_messages_user_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_athlete_profiles_user_id'), table_name='athlete_profiles')
    op.drop_table('athlete_profiles')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_date'), table_name='activities')
    op.drop_index('idx_activities_user_date', table_name='activities')
    op.drop_index('idx_activities_source_id', table_name='activities', postgresql_where=sa.text('source_activity_id IS NOT NULL'), sqlite_where=sa.text('source_activity_id IS NOT NULL'))
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
